language: c

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake

matrix:
  include:
    - os: linux
      env:
        - BUILD_TYPE=make
    - os: linux
      env:
        - BUILD_TYPE=cmake
    - os: osx
      env:
        - BUILD_TYPE=make
        - CFLAGS="-arch i386 -arch x86_64"
        - MAYBE_CONFIG=--enable-shared
    - os: osx
      osx_image: xcode9
      env:
        - BUILD_TYPE=cmake
        - MAYBE_ARCH=-DCMAKE_OSX_ARCHITECTURES="i386;x86_64"
    - os: osx
      osx_image: xcode8.3
      env:
        - BUILD_TYPE=cmake
        - MAYBE_ARCH=-DCMAKE_OSX_ARCHITECTURES="i386;x86_64"
    - os: osx
      osx_image: xcode8.2
      env:
        - BUILD_TYPE=cmake
        - MAYBE_ARCH=-DCMAKE_OSX_ARCHITECTURES="i386;x86_64"
    - os: osx
      osx_image: xcode8.1
      env:
        - BUILD_TYPE=cmake
        - MAYBE_ARCH=-DCMAKE_OSX_ARCHITECTURES="i386;x86_64"
    - os: osx
      osx_image: xcode8
      env:
        - BUILD_TYPE=cmake
        - MAYBE_ARCH=-DCMAKE_OSX_ARCHITECTURES="i386;x86_64"
    - os: osx
      osx_image: xcode7.3
      env:
        - BUILD_TYPE=cmake
        - MAYBE_ARCH=-DCMAKE_OSX_ARCHITECTURES="i386;x86_64"
    - os: osx
      osx_image: xcode6.4
      env:
        - BUILD_TYPE=cmake
        - MAYBE_ARCH=-DCMAKE_OSX_ARCHITECTURES="i386;x86_64"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake || brew upgrade cmake || true; fi

script:
  - if [[ "$BUILD_TYPE" == "make" ]]; then ./configure && make -j 4 && make check -j 4; fi
  - if [[ "$BUILD_TYPE" == "cmake" ]]; then cmake . $MAYBE_ARCH; fi
  - if [[ "$BUILD_TYPE" == "cmake" ]]; then cmake --build . --config Release; fi
  - if [[ "$BUILD_TYPE" == "cmake" ]]; then cmake --build . --config Release --target package; fi

