language: c

matrix:
    include:
        - os: linux
          env:
              - BUILD_TYPE=make

        - os: linux
          env:
              - BUILD_TYPE=cmake

        - os: osx
          env:
              - BUILD_TYPE=make
              - CFLAGS="-arch i386 -arch x86_64"

        - os: osx
          osx_image: xcode9
          env:
              - BUILD_TYPE=cmake
              - MAYBE_ARCH=-DCMAKE_OSX_ARCHITECTURES="i386;x86_64"
              - MAYBE_SHARED=-DBUILD_SHARED_LIBS=ON

        - os: osx
          osx_image: xcode8.3
          env:
              - BUILD_TYPE=cmake
              - MAYBE_ARCH=-DCMAKE_OSX_ARCHITECTURES="i386;x86_64"
              - MAYBE_SHARED=-DBUILD_SHARED_LIBS=ON

        - os: osx
          osx_image: xcode8.2
          env:
              - BUILD_TYPE=cmake
              - MAYBE_ARCH=-DCMAKE_OSX_ARCHITECTURES="i386;x86_64"
              - MAYBE_SHARED=-DBUILD_SHARED_LIBS=ON

        - os: osx
          osx_image: xcode8.1
          env:
              - BUILD_TYPE=cmake
              - MAYBE_ARCH=-DCMAKE_OSX_ARCHITECTURES="i386;x86_64"
              - MAYBE_SHARED=-DBUILD_SHARED_LIBS=ON

        - os: osx
          osx_image: xcode8
          env:
              - BUILD_TYPE=cmake
              - MAYBE_ARCH=-DCMAKE_OSX_ARCHITECTURES="i386;x86_64"
              - MAYBE_SHARED=-DBUILD_SHARED_LIBS=ON

        - os: osx
          osx_image: xcode7.3
          env:
              - BUILD_TYPE=cmake
              - MAYBE_ARCH=-DCMAKE_OSX_ARCHITECTURES="i386;x86_64"
              - MAYBE_SHARED=-DBUILD_SHARED_LIBS=ON

        - os: osx
          osx_image: xcode6.4
          env:
              - BUILD_TYPE=cmake
              - MAYBE_ARCH=-DCMAKE_OSX_ARCHITECTURES="i386;x86_64"
              - MAYBE_SHARED=-DBUILD_SHARED_LIBS=ON

script:
    - if [[ "$BUILD_TYPE" == "make" ]]; then configure && make -j 4 && make check -j 4; fi
    - if [[ "$BUILD_TYPE" == "cmake" ]]; then cmake . $MAYBE_SHARED $MAYBE_ARCH
    - if [[ "$BUILD_TYPE" == "cmake" ]]; then cmake --build . --config Release
    - if [[ "$BUILD_TYPE" == "cmake" ]]; then cmake --build . --target package --config Release


